# Welcome to Jekyll!
#

# Site settings
title: Music in Brighton
email:
description: |
  A site for all things great....
baseurl: "/music" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Site Navigation
navigation:
  - title: Home
    url: /index.html
  - title: Blog
    url: /reviews/index.html
    dropdown:
      - title: Gig Reviews
        url: /blog/gig-reviews.html
      - title: Album Reviews
        url: /blog/album-reviews.html
      - title: Gig Previews
        url: /blog/gig-previews.html
  - title: Gigs
    url: /gigs/index.html
