# Welcome to Jekyll!
#

# Site settings
title: Music in Brighton
email:
description: |
  A site for all things great....
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Site Navigation
navigation:
  - title: Home
    url: /index.html
  - title: Blog
    url: /blog/index.html

social-links:
  - name: twitter
    url: https://twitter.com/benmacdonald8
  - name: email
    url: mailto:gmattgreenfield@gmail.com?subject=Short%20title&body=Brief%20description:%20http%3A%2F%2F/2016/01/08/a-gig.html%2F
