# Welcome to Jekyll!
#

# Site settings
title: Music in Brighton
email:
description: |
  A site for all things great....
baseurl: "/music" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Site Navigation
navigation:
  - title: Home
    url: /index.html
  - title: Reviews
    url: /reviews/index.html
    dropdown:
      - title: Gigs
        url: /reviews/gigs.html
      - title: Albums
        url: /reviews/albums.html
  - title: Gigs
    url: /gigs/index.html
